/*
Package pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package models

import (
    "encoding/json"
    "github.com/apimatic/go-core-runtime/types"
)

// Response object for listing invoices
type ListInvoicesResponse struct {
    Data   types.Optional[[]GetInvoiceResponse] `json:"data"`
    Paging types.Optional[PagingResponse]       `json:"paging"`
}

func (l *ListInvoicesResponse) MarshalJSON() (
    []byte,
    error) {
    return json.Marshal(l.toMap())
}

func (l *ListInvoicesResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    if l.Data.IsValueSet() {
        structMap["data"] = l.Data.Value()
    }
    if l.Paging.IsValueSet() {
        structMap["paging"] = l.Paging.Value()
    }
    return structMap
}

func (l *ListInvoicesResponse) UnmarshalJSON(input []byte) error {
    temp := &struct {
        Data   types.Optional[[]GetInvoiceResponse] `json:"data"`
        Paging types.Optional[PagingResponse]       `json:"paging"`
    }{}
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    
    l.Data = temp.Data
    l.Paging = temp.Paging
    return nil
}
